gcp_credentials: ENCRYPTED[987a78af29b91ce8489594c9ab3fec21845bbe5ba68294b8f6def3cf0d380830f06687a89ea69c87344c5ade369700fe]

gke_container:
 image: gcr.io/flutter-cirrus/build-engine-image:latest
 cluster_name: build-32-cluster
 zone: us-central1-a
 namespace: default
 cpu: 30 # can't use all 30-cores; system pods needs cores too
 memory: 100Gb # similarly, can't use all 100Gb memory

task:
  env:
    CIRRUS_WORKING_DIR: "/tmp/github_repo"

  replace_engine_script: |
    cd $ENGINE_PATH/src
    rm -r flutter
    mv $CIRRUS_WORKING_DIR flutter
    gclient sync

  matrix:
    - name: build_and_test_host
      compile_host_script: |
        cd $ENGINE_PATH/src
        ./flutter/tools/gn --unoptimized
        ninja -C out/host_debug_unopt
      test_host_script: cd $ENGINE_PATH/src && ./flutter/testing/run_tests.sh
    - name: build_android
      compile_host_script: |
        cd $ENGINE_PATH/src
        ./flutter/tools/gn --android --unoptimized
        ninja -C out/android_debug_unopt

format_and_dart_test_task:
  container:
    image: gcr.io/flutter-cirrus/build-engine-image:latest

  env:
    CIRRUS_WORKING_DIR: "/tmp/github_repo"

  replace_engine_script: |
    cd $ENGINE_PATH/src
    rm -r flutter
    cp $CIRRUS_WORKING_DIR -r ./flutter
    gclient sync

  format_script: cd $ENGINE_PATH/src/flutter && ./ci/format.sh
  build_script: cd $ENGINE_PATH/src/flutter && ./ci/build.sh
